#!/usr/bin/env python3
# Generated by fkst-framework init-package-repo.
from pathlib import Path
import os
import stat
import sys


REQUIRED_FILES = [
    "scripts/run.sh",
    "scripts/check_repo.py",
    ".github/workflows/ci.yml",
    "env.example",
    ".fkst-substrate-ref",
]


def fail(message: str) -> None:
    print(f"check_repo.py: {message}", file=sys.stderr)
    sys.exit(1)


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    if not (root / ".git").exists():
        fail("repository root must contain .git")

    for rel in REQUIRED_FILES:
        if not (root / rel).is_file():
            fail(f"missing required scaffold file: {rel}")

    ref = (root / ".fkst-substrate-ref").read_text(encoding="utf-8").strip()
    if not ref:
        fail(".fkst-substrate-ref must not be empty")

    run_sh = root / "scripts/run.sh"
    mode = stat.S_IMODE(os.stat(run_sh).st_mode)
    if mode & stat.S_IXUSR == 0:
        fail("scripts/run.sh must be executable")


if __name__ == "__main__":
    main()
