-- codex-saga locale catalog: flat {key = UTF-8 string}; t(key[, vars]) reads this.
-- These are the OUTWARD strings (spec §10 output contract): the gh issue/comment
-- and PR body templates, the gate refusal reasons, the AI-disclosure line, and the
-- CLA text. Marker/protocol sentinels (HTML comments) are CODE, in core/markers.lua,
-- NOT catalog content (the engine rejects `<!-- fkst:` tokens in locale values).
-- Interpolation placeholders use {name} with name in [A-Za-z0-9_]+.
return {
  -- AI disclosure (mandatory on every public post, spec §10 gate7).
  ["codex-saga.engage.disclose_ai"] = "This analysis was prepared with AI assistance.",

  -- Outward issue/comment dossier (the §3 winning template: repro + root cause +
  -- impact + approach as options + defer + disclosure).
  ["codex-saga.engage.heading"] = "Reproduction notes and proposed fix path",
  ["codex-saga.engage.intro"] = "I took a pass at reducing this to an actionable code path before suggesting a fix.",
  ["codex-saga.engage.breakdown_heading"] = "Breakdown:",
  ["codex-saga.engage.repro_line"] = "I treated the report as reproducible enough to trace against the current code instead of asking for more information.",
  ["codex-saga.engage.root_cause_label"] = "Root cause",
  ["codex-saga.engage.impact_label"] = "Impact",
  ["codex-saga.engage.approach_heading"] = "Proposed approach:",
  ["codex-saga.engage.fix_scope_with_root"] = "Keep the patch scoped to the code path around {root_cause}, so the behavior changes where the regression is introduced rather than broadening the surface area.",
  ["codex-saga.engage.fix_scope_default"] = "Keep the patch scoped to the reproduced failing path instead of broadening adjacent behavior.",
  ["codex-saga.engage.validation_label"] = "Validation plan",
  ["codex-saga.engage.validation_default"] = "add or update focused regression coverage and run the affected package test target before proposing the branch",
  ["codex-saga.engage.branch_label"] = "Prepared fork branch",
  ["codex-saga.engage.invite_policy"] = "I will not open an unsolicited PR; if this direction matches maintainer expectations, I can open the prepared branch for review.",
  ["codex-saga.engage.precedent_label"] = "Precedent",
  ["codex-saga.engage.precedent_none"] = "no closely analogous merged fix found in the worked-on corpus",
  ["codex-saga.engage.learning_heading"] = "How I shaped this comment from prior successful threads:",
  ["codex-saga.engage.modeled_on"] = "Nearest successful examples considered: {count}.",
  ["codex-saga.engage.learning_moves"] = "The shared pattern was to show the repro/root-cause evidence first, state the smallest viable fix, defer to maintainers on direction, and disclose AI assistance.",

  -- Control issue (saga tracker on this harness repo; mirrors saga state on GitHub).
  ["codex-saga.control.title"] = "codex-saga: {dedup_key}",
  ["codex-saga.control.body"] = "Program-produced saga control issue. State transitions are recorded by the harness as labels and markers; do not hand-edit.",

  -- Rich control-issue body (visible "fkst ai log" arguments; markers are appended by code).
  ["codex-saga.control.heading"] = "## Candidate",
  ["codex-saga.control.upstream_label"] = "**Upstream issue**",
  ["codex-saga.control.why_heading"] = "## Why this candidate?",
  ["codex-saga.control.score_label"] = "Priority score",
  ["codex-saga.control.score_note"] = "calibrated rubric (METHODOLOGY §5)",
  ["codex-saga.control.area_label"] = "Area",
  ["codex-saga.control.type_label"] = "Type",
  ["codex-saga.control.detected_label"] = "Detected by",
  ["codex-saga.control.detected_by"] = "codex-triage (rubric + cluster dedup) → codex-saga",
  ["codex-saga.control.pipeline_note"] = "Program-produced saga control issue — do not hand-edit. Live progress is posted as comments below; the current stage is reflected in the `codex-saga:<state>` label.",
  ["codex-saga.control.generated_by"] = "Generated by FKST codex-saga",
  ["codex-saga.control.auto_loop_tag"] = "⟦AI:AUTO-LOOP⟧",

  -- The run plan rendered into every control-issue body (how each phase executes).
  ["codex-saga.control.plan_heading"] = "## Plan",
  ["codex-saga.plan.1"] = "1. **diagnose** — reproduce the report on a read-only fork worktree (codex run), extract root cause at file:line + evidence; not reproduced → `needs-info`.",
  ["codex-saga.plan.2"] = "2. **implement** — codex writes a focused fix on a fork branch (≤3 files / ≤200 LOC, fail-before/pass-after test), imitating merged-PR exemplars.",
  ["codex-saga.plan.3"] = "3. **dossier** — assemble the contribution story: precedent from the worked-on corpus + successful-engagement exemplars; push the fix branch.",
  ["codex-saga.plan.4"] = "4. **gate** — safety routing, invite policy, daily volume cap, AI-disclosure, and multi-angle consensus with a devil's-advocate dissent; refusal → `rejected`.",
  ["codex-saga.plan.5"] = "5. **engage** — post the dossier comment (with AI disclosure) on the upstream issue; then wait for a maintainer invitation.",
  ["codex-saga.plan.6"] = "6. **propose** — only after a recorded invitation: open the fork→upstream PR + CLA; track the outcome to `merged`/`closed`.",

  -- Per-stage "Next:" plan lines on the progress comments.
  ["codex-saga.progress.next.diagnosed"] = "codex writes a focused fix on a fork branch (≤3 files + regression test), imitating merged-PR exemplars (`2/6-implement`).",
  ["codex-saga.progress.next.implemented"] = "assemble the dossier — precedent + engagement exemplars — and push the fix branch (`3/6-dossier`).",
  ["codex-saga.progress.next.dossier"] = "run the gate: safety routing, volume cap, AI-disclosure, and multi-angle consensus with a devil's-advocate dissent (`4/6-gate`).",
  ["codex-saga.progress.next.cleared"] = "post the dossier comment with AI disclosure on the upstream issue (`5/6-engage`).",
  ["codex-saga.progress.next.engaged"] = "poll for a maintainer invitation on this control issue; no uninvited PR will be opened (still `5/6-engage`).",
  ["codex-saga.progress.next.invited"] = "open the fork→upstream pull request + CLA acknowledgement (`6/6-propose`).",
  ["codex-saga.progress.next.proposed"] = "record the attempt outcome durably and watch CI/review until `merged` or `closed`.",

  -- Per-stage progress feed (core.progress): one marker-gated comment per saga state on
  -- the control issue, so the tracker is a live activity board. Program-produced.
  ["codex-saga.progress.diagnosed"] = "Diagnosed: reproduced and root-caused on a fork worktree.",
  ["codex-saga.progress.needs_info"] = "Needs info: dropped before engagement (see reason).",
  ["codex-saga.progress.implemented"] = "Implemented: a focused fix was written on a fork branch.",
  ["codex-saga.progress.dossier"] = "Dossier: contribution story assembled with precedent from the worked-on corpus.",
  ["codex-saga.progress.cleared"] = "Cleared: passed the safety + multi-angle consensus gate.",
  ["codex-saga.progress.refused"] = "Refused at the gate (see reason).",
  ["codex-saga.progress.engaged"] = "Engaged: the dossier comment was posted on the upstream candidate issue.",
  ["codex-saga.progress.invited"] = "Invited: a maintainer invitation was recorded.",
  ["codex-saga.progress.proposed"] = "Proposed: the fork to upstream pull request was opened.",
  ["codex-saga.progress.tracked"] = "Tracked: the attempt outcome was recorded for the learning loop.",
  ["codex-saga.progress.merged"] = "Merged upstream.",
  ["codex-saga.progress.closed"] = "Closed upstream.",

  -- Gate refusal reasons (the WHY carried by the terminal drop, spec §10).
  ["codex-saga.gate.refuse_security"] = "Security or safety issue: routed privately to security@openai.com and never posted publicly.",
  ["codex-saga.gate.refuse_consensus"] = "Multi-angle consensus did not approve this engagement.",
  ["codex-saga.gate.refuse_volume_cap"] = "Daily public engagement cap reached; deferring this engagement.",
  ["codex-saga.gate.refuse_disclosure"] = "AI-disclosure is disabled; refusing to post without disclosing AI assistance.",
  ["codex-saga.gate.refuse_invite_policy"] = "Invitation precondition is disabled; refusing to engage without the no-uninvited-PR safety in place.",

  -- Diagnose drop reasons.
  ["codex-saga.diagnose.needs_info_no_fork"] = "Cannot reproduce locally: no fork checkout is configured.",
  ["codex-saga.diagnose.needs_info_not_reproduced"] = "Could not reproduce the issue locally; dropping to needs_info pending more information.",

  -- Implement (the write-class fix step) drop reasons.
  ["codex-saga.implement.needs_info_no_fork"] = "Cannot write a fix locally: no fork checkout is configured.",
  ["codex-saga.implement.needs_info_no_fix"] = "Could not write a focused fix on the fork; dropping to needs_info pending more information.",

  -- Track (the terminal outcome recorder) heading on the durable control issue.
  ["codex-saga.track.heading"] = "Attempt outcome (program-produced; recorded by the harness for the learning loop).",

  -- PR body + CLA (only after a recorded invitation, spec §10 gate3).
  ["codex-saga.pr.heading"] = "What and why",
  ["codex-saga.pr.linked"] = "This change addresses the diagnosed issue and was developed on a fork.",
  ["codex-saga.pr.cla"] = "I have read the CLA Document and I hereby sign the CLA",
}
